/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'

const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/prontuario': typeof ProntuarioRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/prontuario': typeof ProntuarioRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/prontuario': typeof ProntuarioRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/prontuario'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/prontuario'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/prontuario'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ProntuarioRoute: typeof ProntuarioRoute
  PacientesIdRoute: typeof PacientesIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  ProntuarioRoute: ProntuarioRoute,
  PacientesIdRoute: PacientesIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
